### ISSUE TITLE
Rock paper scissor using html, js, css

### ISSUE THREAD

**Issue by ayush4345** [codeverything/awesome-projects#12]
# Project name rock paper scissor

**About in brief**
basically, the user will be presented with three choices rock, paper, and scissors. based on the choice of the user and the random choice made by the computer user will either lose or win the game.
The logic part is written using javascript.

**Happy Hacking**

**Comment by BasedBrenden** [comment]
Hi, I'd be glad to take a crack at this one if it still needs some help!

**Comment by arindam369** [comment]
please can you assign me this project ?
I have done this project of rock-paper-scissor

**Comment by ayush4345** [comment]
> please can you assign me this project ? I have done this project of rock-paper-scissor

Bro checkout any other project and if u have any other project then make issue for that as it is assigned to me and I have already completed it,I just have to make PR
