### ISSUE TITLE
This repo has been excluded from Hacktoberfest 2022

### ISSUE THREAD

**Issue by Baba-Yaga-1** [codeverything/awesome-projects#125]
# This repo has been excluded from Hacktoberfest 2022.

![Screenshot 2022-10-08 at 13-36-06 Profile Hacktoberfest 2022](https://user-images.githubusercontent.com/56999749/194697335-c0fd577d-71ae-43b8-95b0-35c10d18e10a.png)

**Comment by BWsix** [comment]
Thanks for sharing!
