### ISSUE TITLE
Guess the Number Game

### ISSUE THREAD

**Issue by Pratyay008** [codeverything/awesome-projects#33]
# Guess the Number Game

It is a simple game named 'Guess the Number' using Python programming. Here you have to enter the guessed number between 1 and 100, generated by the computer. And also your best score will be treated as the least number of tries. To run the game ---> First download the codes, then run it on your computer.

**Happy Hacking**

**Comment by redKath** [comment]
Please assign this to me so I can work on it. Thank you.
