### ISSUE TITLE
Drum kit using HTML, CSS and JavaScript

### ISSUE THREAD

**Issue by pandeyom331** [codeverything/awesome-projects#9]
# Drum kit

Different types of instruments will be their, and you will be able to play those instruments using keyboard or by just clicking on them.

Please Assign this to me and add the labels also.

**Happy Hacking**

**Comment by tejasjaiswal07** [comment]
Hey @palanioffcl, can you please assign me to this issue 
thank you!

**Comment by pandeyom331** [comment]
Pull request has been created for this project

**Comment by pandeyom331** [comment]
please accept
